### ISSUE TITLE
OpenVPN config file adjustments

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/tomato-sabai-arm#11]
Remove extra windows characters from openvpn config files, and comment out receive-dns and explicit-exit-notify 2

**Comment by victorcrimea** [comment]
Which config file have to be fixed? It seems that there is no any vpn configs integrated into SabaiOS

**Comment by wmhaynes** [comment]
When you load a vpn file on the openvpn page, then these operations should
be done on that file as it's being saved.  The linux version of openvpn
doesn't like the extra windows characters and the exit-notify statement.

Sincerely,

*William Haynes*
Chief Executive Officer / Founder
Sabai Technology <http://www.sabaitechnology.com/> | RouterSource.com
<http://routersource.com/>
+1
864.962.4072 | +1 864.962.4073

[image: Sabai Technology] <http://www.sabaitechnology.com>  [image: William
Haynes] <https://www.linkedin.com/in/sabaitechnology>  [image: Twitter]
<https://twitter.com/sabaitechnology>  [image: Facebook]
<https://www.facebook.com/sabairouters>

**Comment by victorcrimea** [comment]
Fixed since 6.14
