### ISSUE TITLE
6.14-ARM OpenVPN not functioning

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/tomato-sabai-arm#12]
OpenVPN file will not load, page times out and if I refresh the page I get a message that the file size was too small or too large. 
![image](https://cloud.githubusercontent.com/assets/15368845/13121799/e7f20a50-d581-11e5-879f-def0b88f1240.png)

**Comment by victorcrimea** [comment]
Could you please check is this bug can be reproduced also on 6.13?

**Comment by ruthpetty** [comment]
Sure, let me check that for you.

Sincerely,

Ruth Petty
Sabai Technology
--------------------------------------
p - 1 (864) 962-4072
--------------------------------------
Need help?
<support@sabaitechnology.com> <http://www.meetme.so/Sabai>
--------------------------------------
<https://www.linkedin.com/in/ruth-petty-40a7322a>
<https://twitter.com/sabaitechnology>
<https://www.facebook.com/sabairouters>
--------------------------------------

**Comment by ruthpetty** [comment]
Issue is not present in 6.13

Sincerely,

Ruth Petty
Sabai Technology
--------------------------------------
p - 1 (864) 962-4072
--------------------------------------
Need help?
<support@sabaitechnology.com> <http://www.meetme.so/Sabai>
--------------------------------------
<https://www.linkedin.com/in/ruth-petty-40a7322a>
<https://twitter.com/sabaitechnology>
<https://www.facebook.com/sabairouters>
--------------------------------------

**Comment by victorcrimea** [comment]
Thank you! Now I know where to look for a bug.

**Comment by victorcrimea** [comment]
Fixed since 6.15
