### ISSUE TITLE
DNS issue in OpenVPN 

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/tomato-sabai-arm#13]
OpenVPN configuration file running with a remote address of the name and not the number, as example: usawest.talesxst.com
When the server resyncs, the openvpn configuration gives this error message: 
RESOLVE: Cannot resolve host address: usawest.talesxst.com: [HOST_NOT_FOUND] The specified host is unknown.
If we replace the usawest.talesxst.com with the IP address instead the issue does not present itself. Need to know what is causing this issue in the reconnect.

**Comment by victorcrimea** [comment]
Fixed since 6.16
