### ISSUE TITLE
Corner server information not updating

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/tomato-sabai-arm#16]
"VPN is UP via OpenVPN/PPTP"
Retrieving internet IP address......

Sits on that sometimes forever, never updating, other times it takes it 5-15 minutes to update and of course, if you leave the page and come back you have to start over again with the waiting. I have double checked to make sure that the IP is not banned with that service.

**Comment by victorcrimea** [comment]
Fixed since 6.17
