### ISSUE TITLE
Backup-restore mechanism doesn't work

### ISSUE THREAD

**Issue by victorcrimea** [sabaitechnology/tomato-sabai-arm#5]
Backup created, restored, does not actually make the changes.

**Comment by ruthpetty** [comment]
Confirmed still broken

**Comment by wmhaynes** [comment]
I like the new mechanism.  Please have it save the file as:

sabaios_routertype_date.bak  If it's not too difficult.  This gives tech support a lot of info about the backup and identifies it as a backup file.

**Comment by victorcrimea** [comment]
Implemented since 6.13

**Comment by ruthpetty** [comment]
Backup function is not working from or to 6.15 or 6.18

**Comment by victorcrimea** [comment]
Works from 6.18
