### ISSUE TITLE
Netgear R7000 has wrong version number

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/tomato-sabai-arm#7]
When I use the sabai-R7000-ARM-NETGEAR.trx file in the Drive folder it gives me version 6.08 and does not have the mode option in the 2.4GHz. I reverted to the tomato-R7000--def-ARM-VPN-64K.trx and it is correctly showing version 6.09 and also has the mode button on the 2.4GHz.

**Comment by victorcrimea** [comment]
Seems to be resolved.
